Repository Mergifyio/mergify-engine, pull requests merged in 2020-08, with the labels that each got.

#1306 fix: vcrpy 4 support httpx natively
  mergify_engine/tests/functional/__init__.py
  mergify_engine/tests/functional/base.py
  mergify_engine/tests/functional/httpx_vcr_stubs.py
  setup.cfg
Labels: no-review-needed

#1291 fix(rebase): always run it
  mergify_engine/actions/rebase.py
Labels: enhancement

#1310 fix(rebase): avoid rebasing .github/workflows PR
  mergify_engine/actions/merge/helpers.py
  mergify_engine/actions/rebase.py
  mergify_engine/context.py
Labels: hotfix

#1311 fix(rebase): add missing conclusion
  mergify_engine/actions/rebase.py
Labels: hotfix

#1322 feat(http-client): change default timeout
  mergify_engine/clients/http.py
Labels: manual merge

#1330 fix(worker): do not ignore private repo with no sub
  mergify_engine/worker.py
Labels: hotfix

#1354 fix(worker): never fail to do monitoring
  mergify_engine/worker.py
Labels: hotfix
