Repository Mergifyio/mergify-engine, pull requests merged in 2020-05, with the labels that each got.

#1022 fix: installation can be None in logging
  mergify_engine/tasks/github_events.py
Labels: no-review-needed

#1023 fix: ignore error we have no access to the expected resource
  mergify_engine/exceptions.py
  mergify_engine/worker.py
Labels: no-review-needed

#1025 feat: always raise RateLimit if the 401 is due to rate limit
  mergify_engine/branch_updater.py
  mergify_engine/clients/github.py
  mergify_engine/clients/github_app.py
  mergify_engine/config.py
  mergify_engine/debug.py
  mergify_engine/duplicate_pull.py
  mergify_engine/tests/functional/__init__.py
  mergify_engine/tests/functional/base.py
  mergify_engine/tests/unit/test_clients.py
  mergify_engine/utils.py
  setup.cfg
Labels: no-review-needed

#1026 feat: create only one thread per worker
  mergify_engine/tests/unit/test_worker.py
  mergify_engine/worker.py
Labels: no-review-needed

#1028 feat: upgrade to python 3.7.7
  runtime.txt
Labels: no-review-needed

#1033 fix: don't retry TooManyPages forever
  mergify_engine/worker.py
Labels: no-review-needed

#1035 chore: replace redis xread by xrange
  mergify_engine/worker.py
Labels: no-review-needed

#1038 test: merge rules/config tests
  mergify_engine/tests/unit/rules/test_rules.py
  mergify_engine/tests/unit/test_config.py
Labels: no-review-needed

#1039 fix: check installation instead of data['installation']
  mergify_engine/tasks/github_events.py
Labels: no-review-needed

#1044 fix: some wordings
  mergify_engine/branch_updater.py
  mergify_engine/clients/http.py
Labels: no-review-needed

#1045 feat: change default loglevel to info
  mergify_engine/clients/github.py
  mergify_engine/clients/http.py
  mergify_engine/config.py
  mergify_engine/logs.py
Labels: no-review-needed

#1049 fix: use weakref to store the list of logger
  mergify_engine/logs.py
Labels: no-review-needed

#1052 fix: don't run engine if pull request return 404
  mergify_engine/worker.py
Labels: no-review-needed

#1053 feat: don't return the engine, if mandatory perm are missing
  mergify_engine/clients/github_app.py
  mergify_engine/tests/unit/test_clients.py
Labels: no-review-needed

#1055 fix: ensure base/repo is present for checks
  mergify_engine/github_events.py
Labels: no-review-needed

#1056 fix: check repository/installation first
  mergify_engine/github_events.py
Labels: no-review-needed

#1060 fix: review user can be None
  mergify_engine/context.py
Labels: no-review-needed

#1059 fix: ignore 404 on /pulls
  mergify_engine/exceptions.py
Labels: no-review-needed

#1061 chore(flake8): fix latest flak8 warnings
  mergify_engine/actions/label.py
  mergify_engine/context.py
  mergify_engine/tests/functional/actions/test_assign.py
  mergify_engine/tests/functional/actions/test_label.py
  mergify_engine/tests/functional/test_engine.py
Labels: no-review-needed

#1067 fix: remove exponential retry of RateLimit
  mergify_engine/tests/unit/test_worker.py
  mergify_engine/worker.py
Labels: no-review-needed

#1068 chore: add logging about token flow
  mergify_engine/clients/github.py
  mergify_engine/clients/github_app.py
Labels: no-review-needed

#1069 chore: log request url
  mergify_engine/clients/github.py
Labels: no-review-needed

#1071 revert: "chore: log request url"
  mergify_engine/clients/github.py
Labels: no-review-needed

#1072 fix: create a memory cache of temporary access token
  mergify_engine/clients/github.py
  mergify_engine/tests/functional/base.py
Labels: no-review-needed

#1073 fix: clean the queue when mergify have been uninstalled
  mergify_engine/worker.py
Labels: no-review-needed

#1074 fix: ignore pull request on blocked account
  mergify_engine/exceptions.py
Labels: no-review-needed

#1075 feat: monitoring the new engine latency
  mergify_engine/worker.py
Labels: no-review-needed

#1077 fix: limit exponential retry to 3 attempts
  mergify_engine/worker.py
Labels: no-review-needed

#1079 fix(doc): assign uses template, not a simple string
  doc/source/actions.rst
Labels: no-review-needed

#1081 docs: move strict rebase text in merge action + add explain token
  doc/source/actions.rst
  doc/source/faq.rst
Labels: no-review-needed

#1084 fix: add python-multipart dep
  requirements.txt
  setup.cfg
Labels: no-review-needed

#1092 fix: don't import vcr at runtime
  mergify_engine/worker.py
Labels: no-review-needed

#1100 chore: move some logs to debug
  mergify_engine/worker.py
Labels: no-review-needed

#1101 fix(tests): ensure all httpserver requests have been called
  mergify_engine/tests/unit/test_clients.py
Labels: no-review-needed

#1102 fix: ignore 404 if repo doesn't exists
  mergify_engine/github_events.py
  mergify_engine/worker.py
Labels: no-review-needed

#1104 fix: don't proceed PR does not exists
  mergify_engine/worker.py
Labels: no-review-needed

#1103 build(deps): bump httpx from 0.12.1 to 0.13.1
  mergify_engine/clients/http.py
  mergify_engine/debug.py
  mergify_engine/tests/bridge.py
  mergify_engine/tests/functional/base.py
  requirements.txt
Labels: no-review-needed

#1050 chore: remove some python deprecation
  mergify_engine/tests/functional/test_engine.py
Labels: no-review-needed

#1125 feat: handle AsyncClient retries
  mergify_engine/clients/http.py
  mergify_engine/tests/functional/__init__.py
  mergify_engine/tests/unit/test_clients.py
Labels: manual merge

#1134 fix: ignore some 422 error
  mergify_engine/exceptions.py
Labels: hotfix
