Repository Mergifyio/mergify-engine, pull requests merged in 2022-05, with the labels that each got.

#4562 feat(config): cache config file content into redis
  mergify_engine/context.py
  mergify_engine/engine/__init__.py
  mergify_engine/github_events.py
  mergify_engine/tests/functional/test_configuration.py
  mergify_engine/tests/unit/rules/test_rules.py
  mergify_engine/tests/unit/test_train.py
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/config.json
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/git-1.json
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/http.json
  zfixtures/cassettes/TestDebugger/test_debugger/config.json
  zfixtures/cassettes/TestDebugger/test_debugger/git-1.json
  zfixtures/cassettes/TestDebugger/test_debugger/http.json
  zfixtures/cassettes/TestQueueAction/test_queue_rule_deleted/config.json
  zfixtures/cassettes/TestQueueAction/test_queue_rule_deleted/git-1.json
  zfixtures/cassettes/TestQueueAction/test_queue_rule_deleted/http.json
Labels: Skip documentation, Skip release note

#4639 fix: retry only pull request on HTTP 500
  mergify_engine/worker.py
Labels: hotfix

#4656 feat(queue): add queue configuration list API endpoint
  mergify_engine/tests/functional/api/test_queue.py
  mergify_engine/web/api/queues.py
  releasenotes/notes/queue-config-list-81d16c577c855672.yaml
  zfixtures/cassettes/TestQueueApi/test_get_queues_config_list/config.json
  zfixtures/cassettes/TestQueueApi/test_get_queues_config_list/git-1.json
  zfixtures/cassettes/TestQueueApi/test_get_queues_config_list/http.json
Labels: Skip documentation

#4692 refactor(signals): use entrypoints instead of namespace packages
  mergify_engine/_datadog.py
  mergify_engine/signals.py
  mergify_engine/tests/unit/test_signals.py
  mergify_engine/usage/last_seen.py
  mergify_engine_signals/noop/__init__.py
  mergify_engine_signals/usage/__init__.py
  setup.cfg
Labels: Review Threads Unresolved

#4751 revert: "fix(queue): add message when branch protection is misconfigured (#4748)"
  docs/source/actions/queue.rst
  mergify_engine/actions/queue.py
Labels: hotfix

#4760 fix(config-change): do detection even if initial summary is set
  mergify_engine/constants.py
  mergify_engine/engine/__init__.py
  zfixtures/cassettes/TestCommentAction/test_comment/config.json
  zfixtures/cassettes/TestCommentAction/test_comment/git-1.json
  zfixtures/cassettes/TestCommentAction/test_comment/http.json
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/config.json
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/git-1.json
  zfixtures/cassettes/TestConfiguration/test_cached_config_changes_when_push_event_received/http.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml/config.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml/git-1.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml/http.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml_in_meantime_on_big_pull_request/config.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml_in_meantime_on_big_pull_request/git-1.json
  zfixtures/cassettes/TestConfiguration/test_change_mergify_yml_in_meantime_on_big_pull_request/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/http.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/config.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/git-1.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/http.json
  zfixtures/cassettes/TestQueueFreeze/test_create_queue_freeze/config.json
  zfixtures/cassettes/TestQueueFreeze/test_create_queue_freeze/git-1.json
  zfixtures/cassettes/TestQueueFreeze/test_create_queue_freeze/http.json
  zfixtures/cassettes/TestQueueFreeze/test_delete_queue_freeze/config.json
  zfixtures/cassettes/TestQueueFreeze/test_delete_queue_freeze/git-1.json
  zfixtures/cassettes/TestQueueFreeze/test_delete_queue_freeze/http.json
  zfixtures/cassettes/TestQueueFreeze/test_queue_freeze_with_pr_just_about_to_merge/config.json
  zfixtures/cassettes/TestQueueFreeze/test_queue_freeze_with_pr_just_about_to_merge/git-1.json
  zfixtures/cassettes/TestQueueFreeze/test_queue_freeze_with_pr_just_about_to_merge/http.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/config.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/git-1.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/git-2.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/http.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_uptodate_pr_branch/config.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_uptodate_pr_branch/git-1.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_uptodate_pr_branch/git-2.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_uptodate_pr_branch/http.json
Labels: hotfix
