Repository Mergifyio/mergify-engine, pull requests merged in 2022-04, with the labels that each got.

#4387 fix(onpremise): use correct graphql url for edit action
  mergify_engine/actions/edit.py
  mergify_engine/clients/github.py
  releasenotes/notes/edit-action-url-b4b3ef063e02439d.yaml
  zfixtures/cassettes/TestEditAction/test_draft_already_converted/config.json
  zfixtures/cassettes/TestEditAction/test_draft_already_converted/git-1.json
  zfixtures/cassettes/TestEditAction/test_draft_already_converted/http.json
  zfixtures/cassettes/TestEditAction/test_draft_to_ready_for_review/config.json
  zfixtures/cassettes/TestEditAction/test_draft_to_ready_for_review/git-1.json
  zfixtures/cassettes/TestEditAction/test_draft_to_ready_for_review/http.json
  zfixtures/cassettes/TestEditAction/test_pr_to_draft_edit/config.json
  zfixtures/cassettes/TestEditAction/test_pr_to_draft_edit/git-1.json
  zfixtures/cassettes/TestEditAction/test_pr_to_draft_edit/http.json
  zfixtures/cassettes/TestEditAction/test_ready_for_review_already_converted/config.json
  zfixtures/cassettes/TestEditAction/test_ready_for_review_already_converted/git-1.json
  zfixtures/cassettes/TestEditAction/test_ready_for_review_already_converted/http.json
Labels: hotfix

#4367 fix(queue): change checks_timeout scope and processing
  mergify_engine/actions/merge_base.py
  mergify_engine/date.py
  mergify_engine/queue/merge_train.py
  mergify_engine/rules/__init__.py
  mergify_engine/tests/functional/actions/test_queue.py
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_draft_pr/config.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_draft_pr/git-1.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_draft_pr/http.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_inplace/config.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_inplace/git-1.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_inplace/http.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_outside_schedule_without_unqueuing/config.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_outside_schedule_without_unqueuing/git-1.json
  zfixtures/cassettes/TestQueueAction/test_queue_ci_timeout_outside_schedule_without_unqueuing/http.json
  zfixtures/cassettes/TestTrainApiCalls/test_create_pull_basic/config.json
  zfixtures/cassettes/TestTrainApiCalls/test_create_pull_basic/git-1.json
  zfixtures/cassettes/TestTrainApiCalls/test_create_pull_basic/http.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch/config.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch/git-1.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch/http.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_multiple_queue/config.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_multiple_queue/git-1.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_multiple_queue/http.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_no_cars/config.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_no_cars/git-1.json
  zfixtures/cassettes/TestTrainApiCalls/test_delete_unused_merge_queue_branch_no_cars/http.json
Labels: Review Threads Unresolved

#4398 fix(tests): be more flexible about number of commit in draft PR
  mergify_engine/tests/functional/actions/test_queue.py
Labels: hotfix

#4399 fix(installer): bootstrap 5 compat
  installer/src/App.jsx
Labels: hotfix

#4397 fix(tests): skip required_conversation_resolution tests on GHES
  mergify_engine/tests/functional/actions/test_merge.py
Labels: hotfix

#4424 chore(queue): add logging to merge-queue pr creation
  mergify_engine/queue/merge_train.py
Labels: hotfix

#4437 fix: handle when forked repository is deleted
  mergify_engine/branch_updater.py
  mergify_engine/github_types.py
  mergify_engine/queue/merge_train.py
  mergify_engine/squash_pull.py
Labels: hotfix

#4442 fix(queue): remove pull requests cleanup
  mergify_engine/queue/merge_train.py
Labels: hotfix

#4444 refactor(queue): move existence check of draft pull request
  mergify_engine/queue/merge_train.py
Labels: hotfix

#4456 feat(config): cache loaded config in Repository context
  mergify_engine/context.py
  mergify_engine/debug.py
  mergify_engine/engine/__init__.py
  mergify_engine/queue/__init__.py
  mergify_engine/queue/merge_train.py
  mergify_engine/rules/__init__.py
  mergify_engine/rules/live_resolvers.py
  mergify_engine/tests/unit/rules/test_rules.py
  mergify_engine/tests/unit/test_train.py
Labels: Skip documentation, Skip release note

#4465 fix(queue): add missing import
  mergify_engine/queue/merge_train.py
Labels: hotfix

#4470 fix(engine): don't handle pull request with more than 500 check-runs
  mergify_engine/check_api.py
  mergify_engine/clients/github.py
  mergify_engine/exceptions.py
  mergify_engine/worker.py
Labels: Review Threads Unresolved

#4476 fix(rules): add string check for batch_max_wait_time
  mergify_engine/rules/__init__.py
  mergify_engine/tests/unit/rules/test_rules.py
Labels: hotfix

#4473 refactor(worker): improve handling of UnprocessablePullRequest exception
  mergify_engine/check_api.py
  mergify_engine/context.py
  mergify_engine/tests/functional/test_engine.py
  mergify_engine/worker.py
  zfixtures/cassettes/TestEngineV2Scenario/test_command_refresh/config.json
  zfixtures/cassettes/TestEngineV2Scenario/test_command_refresh/git-1.json
  zfixtures/cassettes/TestEngineV2Scenario/test_command_refresh/http.json
  zfixtures/cassettes/TestEngineV2Scenario/test_set_summary_with_broken_checks/config.json
  zfixtures/cassettes/TestEngineV2Scenario/test_set_summary_with_broken_checks/git-1.json
  zfixtures/cassettes/TestEngineV2Scenario/test_set_summary_with_broken_checks/http.json
  zfixtures/cassettes/TestSubscription/test_subscription/config.json
  zfixtures/cassettes/TestSubscription/test_subscription/git-1.json
  zfixtures/cassettes/TestSubscription/test_subscription/http.json
Labels: Review Threads Unresolved

#4481 fix(context): handle huge PR gracefully
  mergify_engine/context.py
Labels: hotfix

#4483 fix(labels): increase a bit number of page for labels
  mergify_engine/context.py
Labels: hotfix

#4491 fix(summary): truncate summary correctly
  mergify_engine/check_api.py
  mergify_engine/tests/unit/test_utils.py
  mergify_engine/utils.py
Labels: Review Threads Unresolved

#4496 fix(command): do permission check after command lookup
  mergify_engine/engine/commands_runner.py
  mergify_engine/tests/unit/test_command.py
Labels: hotfix

#4524 fix(context): increase page limit for files api
  mergify_engine/context.py
Labels: hotfix

#4583 revert: "chore(deps): bump google-github-actions/upload-cloud-storage from 0.9.0 to 0.10.0"
  .github/workflows/docs-upload-gcp-prod.yaml
  .github/workflows/docs-upload-gcp.yaml
Labels: hotfix

#4582 feat: add simulator to API
  mergify_engine/rules/__init__.py
  mergify_engine/tests/functional/api/test_simulator.py
  mergify_engine/web/api/root.py
  mergify_engine/web/api/simulator.py
  zfixtures/cassettes/TestApiSimulator/test_simulator_invalid_json/config.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_invalid_json/git-1.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_invalid_json/http.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_token/config.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_token/git-1.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_token/http.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/config.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/git-1.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/http.json
Labels: Skip documentation, Skip release note

#4615 fix(simulator): return 404/401/403 to caller
  mergify_engine/tests/functional/api/test_simulator.py
  mergify_engine/web/api/simulator.py
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/config.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/git-1.json
  zfixtures/cassettes/TestApiSimulator/test_simulator_with_wrong_pull_request_url/http.json
Labels: hotfix

#4624 feat(commits-behind): return only the number
  docs/source/conditions.rst
  mergify_engine/context.py
  mergify_engine/github_types.py
  mergify_engine/rules/parser.py
  mergify_engine/tests/functional/actions/test_merge.py
  mergify_engine/tests/functional/test_attributes.py
  mergify_engine/tests/functional/test_debug.py
  mergify_engine/tests/unit/rules/test_parser.py
  releasenotes/notes/commits-behind-f2efc7e0f92b3aa5.yaml
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_after/config.json
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_after/git-1.json
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_after/http.json
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_before/config.json
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_before/git-1.json
  zfixtures/cassettes/TestAttributes/test_commits_behind_conditions_pr_open_before/http.json
  zfixtures/cassettes/TestAttributes/test_draft/config.json
  zfixtures/cassettes/TestAttributes/test_draft/git-1.json
  zfixtures/cassettes/TestAttributes/test_draft/http.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_rebase_ok/config.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_rebase_ok/git-1.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_rebase_ok/git-2.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_rebase_ok/http.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_update/config.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_update/git-1.json
  zfixtures/cassettes/TestBranchUpdatePublic/test_command_update/http.json
  zfixtures/cassettes/TestCommandUpdate/test_command_update_noop/config.json
  zfixtures/cassettes/TestCommandUpdate/test_command_update_noop/git-1.json
  zfixtures/cassettes/TestCommandUpdate/test_command_update_noop/http.json
  zfixtures/cassettes/TestDebugger/test_debugger/config.json
  zfixtures/cassettes/TestDebugger/test_debugger/git-1.json
  zfixtures/cassettes/TestDebugger/test_debugger/http.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/config.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/git-1.json
  zfixtures/cassettes/TestMergeAction/test_merge_branch_protection_strict/http.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_basic/config.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_basic/git-1.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_basic/http.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_bot_account/config.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_bot_account/git-1.json
  zfixtures/cassettes/TestMergeAction/test_merge_fastforward_bot_account/http.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_ok/config.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_ok/git-1.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_ok/git-2.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_ok/http.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/config.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/git-1.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/git-2.json
  zfixtures/cassettes/TestRebaseAction/test_rebase_on_closed_pr_deleted_branch/http.json
  zfixtures/cassettes/TestUpdateAction/test_update_action/config.json
  zfixtures/cassettes/TestUpdateAction/test_update_action/git-1.json
  zfixtures/cassettes/TestUpdateAction/test_update_action/http.json
  zfixtures/cassettes/TestUpdateAction/test_update_action_on_closed_pr_deleted_branch/config.json
  zfixtures/cassettes/TestUpdateAction/test_update_action_on_closed_pr_deleted_branch/git-1.json
  zfixtures/cassettes/TestUpdateAction/test_update_action_on_closed_pr_deleted_branch/http.json
Labels: Review Threads Unresolved
