Repository Mergifyio/mergify-engine, pull requests merged in 2022-06, with the labels that each got.

#4797 docs: fix typo on merge method to use
  docs/source/actions/queue.rst
Labels: hotfix

#4801 fix(ddtrace): workaround for missing ddtrace pinning
  mergify_engine/__init__.py
Labels: hotfix

#4803 feat(redis): override service name
  mergify_engine/redis_utils.py
Labels: hotfix, Skip documentation, Skip release note

#4784 refactor(redis): split team/user permissions/members cache
  mergify_engine/config.py
  mergify_engine/context.py
  mergify_engine/github_events.py
  mergify_engine/logs.py
  mergify_engine/redis_utils.py
  mergify_engine/tests/conftest.py
  mergify_engine/tests/functional/base.py
  mergify_engine/tests/unit/test_config.py
  mergify_engine/tests/unit/test_context.py
  run-tests.sh
Labels: hotfix

#4822 feat(engine): allow mergify app to be pinged with its url
  mergify_engine/engine/commands_runner.py
  mergify_engine/tests/unit/test_command.py
Labels: Skip documentation, Skip release note

#4841 feat(eventlogs): add dismiss_review event
  mergify_engine/eventlogs.py
  mergify_engine/tests/functional/actions/test_dismiss_review.py
  mergify_engine/web/api/eventlogs.py
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_attribute_error/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_attribute_error/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_attribute_error/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_syntax_error/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_syntax_error/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_custom_message_syntax_error/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_from_requested_reviewers/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_from_requested_reviewers/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_from_requested_reviewers/http.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_ignored/config.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_ignored/git-1.json
  zfixtures/cassettes/TestDismissReviewsAction/test_dismiss_reviews_ignored/http.json
Labels: Skip documentation, Skip release note

#4867 feat(eventlogs): add all signaled events
  mergify_engine/actions/dismiss_reviews.py
  mergify_engine/eventlogs.py
  mergify_engine/signals.py
  mergify_engine/tests/conftest.py
  mergify_engine/web/api/eventlogs.py
Labels: Skip documentation, Skip release note

#4881 feat(tools): Add a custom version of updatecli
  .github/clifus.yml
  .github/get-latest-python-version.py
  .github/updatecli.yml
  .github/workflows/clifus.yaml
  .github/workflows/updatecli.yaml
  tools/clifus.py
Labels: Skip documentation, Skip release note

#4902 feat(eventlogs): add what trigger the action
  mergify_engine/_datadog.py
  mergify_engine/actions/assign.py
  mergify_engine/actions/close.py
  mergify_engine/actions/comment.py
  mergify_engine/actions/copy.py
  mergify_engine/actions/delete_head_branch.py
  mergify_engine/actions/dismiss_reviews.py
  mergify_engine/actions/label.py
  mergify_engine/actions/merge.py
  mergify_engine/actions/merge_base.py
  mergify_engine/actions/post_check.py
  mergify_engine/actions/queue.py
  mergify_engine/actions/rebase.py
  mergify_engine/actions/refresh.py
  mergify_engine/actions/request_reviews.py
  mergify_engine/actions/requeue.py
  mergify_engine/actions/review.py
  mergify_engine/actions/squash.py
  mergify_engine/actions/unqueue.py
  mergify_engine/actions/update.py
  mergify_engine/engine/commands_runner.py
  mergify_engine/eventlogs.py
  mergify_engine/rules/__init__.py
  mergify_engine/signals.py
  mergify_engine/tests/functional/actions/test_dismiss_review.py
  mergify_engine/tests/functional/actions/test_label.py
  mergify_engine/tests/unit/test_count_seats.py
  mergify_engine/tests/unit/test_signals.py
  mergify_engine/usage/last_seen.py
Labels: Skip documentation, Skip release note

#4916 revert: "ci(reqs): rename requirements to constraints"
  .github/workflows/ci.yaml
  .mergify.yml
  constraints.txt
  tox.ini
Labels: hotfix

#4915 feat(signals): track more queue events
  mergify_engine/actions/queue.py
  mergify_engine/actions/unqueue.py
  mergify_engine/engine/actions_runner.py
  mergify_engine/eventlogs.py
  mergify_engine/queue/__init__.py
  mergify_engine/queue/merge_train.py
  mergify_engine/signals.py
  mergify_engine/tests/functional/actions/test_queue.py
  mergify_engine/tests/unit/test_train.py
Labels: Skip documentation, Skip release note

#4938 feat(eventlogs): store it per repository too
  mergify_engine/eventlogs.py
  mergify_engine/tests/functional/actions/test_dismiss_review.py
  mergify_engine/tests/functional/actions/test_label.py
  mergify_engine/tests/functional/api/test_eventlogs.py
  mergify_engine/web/api/eventlogs.py
  zfixtures/cassettes/TestEventLogsAction/test_eventlogs/config.json
  zfixtures/cassettes/TestEventLogsAction/test_eventlogs/git-1.json
  zfixtures/cassettes/TestEventLogsAction/test_eventlogs/http.json
Labels: Skip documentation, Skip release note

#4931 feat(worker): preload/reload redis scripts dynamically on client connection
  mergify_engine/redis_utils.py
  mergify_engine/tests/conftest.py
  mergify_engine/web/redis.py
  mergify_engine/worker.py
Labels: Skip documentation, Skip release note

#4976 fix(queue): ensure signal emit a valid checks_conclusion
  mergify_engine/queue/merge_train.py
  mergify_engine/signals.py
Labels: hotfix

#4980 fix(eventlogs): Don't enforce that all fields should be there
  mergify_engine/signals.py
Labels: hotfix
