Repository Mergifyio/mergify-engine, pull requests merged in 2022-03, with the labels that each got.

#4199 feat(datadog): add tracer for YAML safe_load
  mergify_engine/rules/__init__.py
Labels: Skip documentation, Skip release note

#4221 fix(checks): handle check-runs 422 when commit has been deleted
  mergify_engine/check_api.py
Labels: hotfix

#4243 fix(rules): cast InvalidDatetime exception
  mergify_engine/rules/__init__.py
  mergify_engine/tests/unit/rules/test_rules.py
Labels: hotfix

#4270 feat(crypto): Add mechanism to rotate oauth tokens SECRET
  mergify_engine/config.py
  mergify_engine/crypto.py
  mergify_engine/tests/unit/test_crypto.py
Labels: Skip documentation, Skip release note

#4303 feat(sentry): set gh_owner in worker
  mergify_engine/worker.py
Labels: Skip documentation, Skip release note, Review Threads Unresolved

#4307 fix(duplicate): don't retry non-fast-forward update
  mergify_engine/duplicate_pull.py
Labels: hotfix

#4312 fix(queue): deserialization of old EmbarkedPull format
  mergify_engine/queue/merge_train.py
  mergify_engine/tests/unit/test_train.py
Labels: hotfix

#4359 chore(debug): print default branch name
  mergify_engine/debug.py
  mergify_engine/tests/functional/test_debug.py
Labels: Skip documentation, Skip release note

#4361 fix(queue): add traincar deserialization compat
  mergify_engine/queue/merge_train.py
Labels: hotfix
